stages:
  - build
  - test
  - package

build:
  stage: build
  image: maven:3.9-openjdk-21
  script:
    - cd CSC3065_Valid_IP/Valid_IP
    - mvn clean compile
  artifacts:
    paths:
      - CSC3065_Valid_IP/Valid_IP/target/

test:
  stage: test
  image: maven:3.9-openjdk-21
  script:
    - cd CSC3065_Valid_IP/Valid_IP
    - mvn test
  dependencies:
    - build

package:
  stage: package
  image: maven:3.9-openjdk-21
  script:
    - cd CSC3065_Valid_IP/Valid_IP
    - mvn package -DskipTests
  artifacts:
    paths:
      - CSC3065_Valid_IP/Valid_IP/target/*.jar
  dependencies:
    - build
