stages:
  - test
  - build
  - deploy

test-node:
  stage: test
  image: node:18
  script:
    - cd node-bad-ip
    - npm install
    - npm test

build-node:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd node-bad-ip
    - docker build -t node-bad-ip:latest .
